
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label label6;
	private global::Gtk.HBox hbox2;
	private global::Gtk.ScrolledWindow swGameList;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Label lblGameName;
	private global::Gtk.Image imgGame;
	private global::Gtk.Label lblGameYear;
	private global::Gtk.Label label7;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MonoFe");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.HeightRequest = 80;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
		this.vbox3.Add (this.label6);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label6]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.swGameList = new global::Gtk.ScrolledWindow ();
		this.swGameList.CanFocus = true;
		this.swGameList.Name = "swGameList";
		this.swGameList.ShadowType = ((global::Gtk.ShadowType)(1));
		this.hbox2.Add (this.swGameList);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.swGameList]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.WidthRequest = 310;
		this.fixed4.HeightRequest = 600;
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblGameName = new global::Gtk.Label ();
		this.lblGameName.WidthRequest = 300;
		this.lblGameName.HeightRequest = 30;
		this.lblGameName.Name = "lblGameName";
		this.lblGameName.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
		this.lblGameName.Justify = ((global::Gtk.Justification)(2));
		this.fixed4.Add (this.lblGameName);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.lblGameName]));
		w3.Y = 10;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.imgGame = new global::Gtk.Image ();
		this.imgGame.WidthRequest = 300;
		this.imgGame.HeightRequest = 300;
		this.imgGame.Name = "imgGame";
		this.fixed4.Add (this.imgGame);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.imgGame]));
		w4.Y = 50;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.lblGameYear = new global::Gtk.Label ();
		this.lblGameYear.WidthRequest = 300;
		this.lblGameYear.HeightRequest = 30;
		this.lblGameYear.Name = "lblGameYear";
		this.lblGameYear.LabelProp = global::Mono.Unix.Catalog.GetString ("label5");
		this.fixed4.Add (this.lblGameYear);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.lblGameYear]));
		w5.Y = 360;
		this.hbox2.Add (this.fixed4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed4]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.HeightRequest = 80;
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
		this.vbox3.Add (this.label7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label7]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 942;
		this.DefaultHeight = 927;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.swGameList.SelectionNotifyEvent += new global::Gtk.SelectionNotifyEventHandler (this.selectGame);
	}
}
